Basic OpenBSD's PF rules implemented (closes #19).

diff --git a/easy-wg-quick b/easy-wg-quick
--- a/easy-wg-quick
+++ b/easy-wg-quick
@@ -32,9 +32,9 @@ check_if_wg_is_installed() {
 }
 
 detect_ext_net_if() {
-    if [ "x$(uname -s)" = "xFreeBSD" ]; then
+    if test "x$(uname -s)" = "xFreeBSD"; then
         route get default | awk '$1 == "interface:" { print $2 }'
-    elif [ "x$(uname -s)" = "xLinux" ]; then
+    elif test "x$(uname -s)" = "xLinux"; then
         ip route sh | awk '$1 == "default" { print $5 }'
     fi
 }
@@ -54,9 +54,9 @@ get_ext_net_if() {
 }
 
 detect_ext_net_ip() {
-    if [ "x$(uname -s)" = "xFreeBSD" ]; then
+    if test "x$(uname -s)" = "xFreeBSD"; then
         ifconfig "$1" | awk '$1 == "inet" { print $2 }'
-    elif [ "x$(uname -s)" = "xLinux" ]; then
+    elif test "x$(uname -s)" = "xLinux"; then
         ip addr sh "$1" | grep 'inet ' | xargs | awk -F'[ /]' '{ print $2 }'
     fi
 }
@@ -75,13 +75,36 @@ get_ext_net_ip() {
     cat extnetip.txt
 }
 
+detect_fw_type() {
+    if test "x$(uname -s)" = "xFreeBSD"; then
+        echo "pf"
+    elif test "x$(uname -s)" = "xLinux"; then
+        echo "iptables"
+    fi
+}
+
+create_fw_type() {
+    echo "No fwtype.txt... creating one!"
+    detect_fw_type > fwtype.txt
+    test -s fwtype.txt || {
+        echo 'Unable to detect firewall type.'
+        echo 'Set it manually in fwtype.txt file and star script again.'
+        exit 1
+    }
+}
+
+get_fw_type() {
+    cat fwtype.txt
+}
+
 check_if_ipv6_is_available() {
-    if [ "x$(uname -s)" = "xFreeBSD" ]; then
-        test -n "$(ifconfig $1 | awk '$1 == "inet6" { print $2 }' | grep -v %$1$)" >/dev/null 2>&1 && {
+    if test "x$(uname -s)" = "xFreeBSD"; then
+        IPV6ADR=$(ifconfig "$1" | awk '$1 == "inet6" { print $2 }' | grep -v "%$1$")
+        test -n "$IPV6ADR" && {
             echo 'Looks like you have IPv6 available. Enabling IPv6 in tunnels!'
             return  0
         }
-    elif [ "x$(uname -s)" = "xLinux" ]; then
+    elif test "x$(uname -s)" = "xLinux"; then
         ip -6 addr | grep -i 'scope global' >/dev/null 2>&1 && {
             echo 'Looks like you have IPv6 available. Enabling IPv6 in tunnels!'
             return  0
@@ -127,15 +150,8 @@ create_hub_key() {
     wg genkey > wghub.key
 }
 
-create_hub_conf() {
-    echo "No wghub.conf... creating one!"
-    cat > wghub.conf << EOF
-[Interface]
-Address = $INT_NET_HUB_IP$INT_NET_MASK
-ListenPort = $EXT_NET_PORT
-PrivateKey = $(cat wghub.key)
-SaveConfig = false
-
+create_iptables_rules() {
+    cat << EOF
 PostUp = iptables -t mangle -A POSTROUTING -p tcp --tcp-flags SYN,RST SYN -o $EXT_NET_IF -j TCPMSS --clamp-mss-to-pmtu
 PostUp = ip6tables -t mangle -A POSTROUTING -p tcp --tcp-flags SYN,RST SYN -o $EXT_NET_IF -j TCPMSS --clamp-mss-to-pmtu
 PostUp = iptables -t nat -A POSTROUTING -o $EXT_NET_IF -j MASQUERADE
@@ -154,6 +170,44 @@ PostDown = ip6tables -t nat -D POSTROUTING -o $EXT_NET_IF -j MASQUERADE
 PostDown = iptables -t mangle -D POSTROUTING -p tcp --tcp-flags SYN,RST SYN -o $EXT_NET_IF -j TCPMSS --clamp-mss-to-pmtu
 PostDown = ip6tables -t mangle -D POSTROUTING -p tcp --tcp-flags SYN,RST SYN -o $EXT_NET_IF -j TCPMSS --clamp-mss-to-pmtu
 EOF
+}
+
+create_pf_rules() {
+    cat << EOF
+PostUp = printf 'nat on $EXT_NET_IF from %i:network to any -> ($EXT_NET_IF)\\npass all\\n' | pfctl -f -
+PostUp = pfctl -e
+PostUp = sysctl net.inet.ip.forwarding=1
+PostUp = sysctl net.inet6.ip6.forwarding=1
+
+PostDown = sysctl net.inet.ip.forwarding=0
+PostDown = sysctl net.inet6.ip6.forwarding=0
+PostDown = pfctl -d
+PostDown = printf '' | pfctl -f -
+EOF
+}
+
+create_hub_conf() {
+    echo "No wghub.conf... creating one!"
+    cat > wghub.conf << EOF
+[Interface]
+Address = $INT_NET_HUB_IP$INT_NET_MASK
+ListenPort = $EXT_NET_PORT
+PrivateKey = $(cat wghub.key)
+SaveConfig = false
+
+EOF
+
+    if test "x$FW_TYPE" = "xiptables"; then
+        create_iptables_rules >> wghub.conf
+    elif test "x$FW_TYPE" = "xpf"; then
+        create_pf_rules >> wghub.conf
+    elif test "x$FW_TYPE" = "xcustom"; then
+        echo '# Custom PostUp / PostDown commands from commands.txt' >> wghub.conf
+        cat commands.txt >> wghub.conf
+    elif test "x$FW_TYPE" = "xnone"; then
+        echo '# PostUp / PostDown commands disabled with "none" set in fwtype.txt' >> wghub.conf
+    fi
+
     echo "Wireguard hub address is $EXT_NET_IP:$EXT_NET_PORT on $EXT_NET_IF."
     echo "Note: customize [Interface] section of wghub.conf if required!"
 }
@@ -267,6 +321,9 @@ main() {
     INT_NET_DNS="1.1.1.1"
     INT_NET_PEER="10.127.0."
     INT_NET_PEER_MASK="/32"
+
+    test -f fwtype.txt || create_fw_type
+    FW_TYPE="$(get_fw_type)"
 
     NET6=false
     check_if_ipv6_is_available "$EXT_NET_IF" && {
