Add support for disabling sysctl usage (#24).

diff --git a/easy-wg-quick b/easy-wg-quick
--- a/easy-wg-quick
+++ b/easy-wg-quick
@@ -1,6 +1,6 @@
 #!/bin/sh
 # easy-wg-quick - Creates Wireguard configuration for hub and peers with ease
-# Copyright (C) 2019 Krzysztof Burghardt <krzysztof@burghardt.pl>
+# Copyright (C) 2019, 2020 Krzysztof Burghardt <krzysztof@burghardt.pl>
 #
 #
 # License
@@ -97,6 +97,28 @@ get_fw_type() {
     cat fwtype.txt
 }
 
+detect_sysctl_type() {
+    if test "x$(uname -s)" = "xFreeBSD"; then
+        echo "freebsd"
+    elif test "x$(uname -s)" = "xLinux"; then
+        echo "linux"
+    fi
+}
+
+create_sysctl_type() {
+    echo "No sysctltype.txt... creating one!"
+    detect_sysctl_type > sysctltype.txt
+    test -s sysctltype.txt || {
+        echo 'Unable to detect sysctl type.'
+        echo 'Set it manually in sysctltype.txt file and start script again.'
+        exit 1
+    }
+}
+
+get_sysctl_type() {
+    cat sysctltype.txt
+}
+
 check_if_ipv6_is_available() {
     if test "x$(uname -s)" = "xFreeBSD"; then
         IPV6ADR=$(ifconfig "$1" | awk '$1 == "inet6" { print $2 }' | grep -v "%$1$")
@@ -181,11 +203,6 @@ PostUp = iptables -t nat -A POSTROUTING -o $EXT_NET_IF -j MASQUERADE
 PostUp = ip6tables -t nat -A POSTROUTING -o $EXT_NET_IF -j MASQUERADE
 PostUp = iptables -A FORWARD -i %i -j ACCEPT
 PostUp = ip6tables -A FORWARD -i %i -j ACCEPT
-PostUp = sysctl -q -w net.ipv4.ip_forward=1
-PostUp = sysctl -q -w net.ipv6.conf.all.forwarding=1
-
-PostDown = sysctl -q -w net.ipv4.ip_forward=0
-PostDown = sysctl -q -w net.ipv6.conf.all.forwarding=0
 PostDown = iptables -D FORWARD -i %i -j ACCEPT
 PostDown = ip6tables -D FORWARD -i %i -j ACCEPT
 PostDown = iptables -t nat -D POSTROUTING -o $EXT_NET_IF -j MASQUERADE
@@ -195,17 +212,30 @@ PostDown = ip6tables -t mangle -D POSTROUTING -p tcp --tcp-flags SYN,RST SYN -o 
 EOF
 }
 
+create_sysctl_linux_rules() {
+    cat << EOF
+PostUp = sysctl -q -w net.ipv4.ip_forward=1
+PostUp = sysctl -q -w net.ipv6.conf.all.forwarding=1
+PostDown = sysctl -q -w net.ipv4.ip_forward=0
+PostDown = sysctl -q -w net.ipv6.conf.all.forwarding=0
+EOF
+}
+
 create_pf_rules() {
     cat << EOF
 PostUp = printf 'nat on $EXT_NET_IF from %i:network to any -> ($EXT_NET_IF)\\npass all\\n' | pfctl -f -
 PostUp = pfctl -e
-PostUp = sysctl net.inet.ip.forwarding=1
-PostUp = sysctl net.inet6.ip6.forwarding=1
-
-PostDown = sysctl net.inet.ip.forwarding=0
-PostDown = sysctl net.inet6.ip6.forwarding=0
 PostDown = pfctl -d
 PostDown = printf '' | pfctl -f -
+EOF
+}
+
+create_sysctl_freebsd_rules() {
+    cat << EOF
+PostUp = sysctl net.inet.ip.forwarding=1
+PostUp = sysctl net.inet6.ip6.forwarding=1
+PostDown = sysctl net.inet.ip.forwarding=0
+PostDown = sysctl net.inet6.ip6.forwarding=0
 EOF
 }
 
@@ -217,13 +247,18 @@ Address = $INT_NET_HUB_IP$INT_NET_MASK$($NET6 && echo ", $INT_NET6_HUB_IP$INT_NE
 ListenPort = $EXT_NET_PORT
 PrivateKey = $(cat wghub.key)
 SaveConfig = false
-
 EOF
 
     if test "x$FW_TYPE" = "xiptables"; then
         create_iptables_rules >> wghub.conf
+        if test "x$SYSCTL_TYPE" = "xlinux"; then
+            create_sysctl_linux_rules >> wghub.conf
+        fi
     elif test "x$FW_TYPE" = "xpf"; then
         create_pf_rules >> wghub.conf
+        if test "x$SYSCTL_TYPE" = "xfreebsd"; then
+            create_sysctl_freebsd_rules >> wghub.conf
+        fi
     elif test "x$FW_TYPE" = "xcustom"; then
         echo '# Custom PostUp / PostDown commands from commands.txt' >> wghub.conf
         cat commands.txt >> wghub.conf
@@ -348,6 +383,8 @@ main() {
 
     test -f fwtype.txt || create_fw_type
     FW_TYPE="$(get_fw_type)"
+    test -f sysctltype.txt || create_sysctl_type
+    SYSCTL_TYPE="$(get_sysctl_type)"
 
     NET6=false
     check_if_ipv6_is_available "$EXT_NET_IF" && {
